if (WIN32)
	set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreadedDLL")
	add_compile_options("/MD")
endif()
option(UIMGUI_SKIP_FRAMEWORK "Enable this option in order to compile directly with the system framework" OFF)