include(GenericUnix)

macro(setup_vulkan_vendored)
    set(VULKAN_LIBRARIES_T "vulkan")
    add_subdirectory("${UIMGUI_SRC_PREFIX}/Framework/ThirdParty/vulkan-headers")
endmacro()

macro(setup_opengl_vendored)
    set(OPENGL_LIBRARIES_T "OpenGL")
    set(X11_LIBRARIES "X11")
endmacro()

macro(setup_opengl_system)
    find_package(X11 REQUIRED)
    setup_opengl_system_generic()
endmacro()

macro(setup_platform_os_module)
    option(ENABLE_XDG_BASEDIR "Compile in the UntitledXDGBasedir library for a XDG Basedir implementation" OFF)
    if (ENABLE_XDG_BASEDIR)
        if (BUILD_VARIANT_VENDOR)
            add_subdirectory("${UIMGUI_SRC_PREFIX}/Framework/Modules/OS/ThirdParty/UntitledXDGBasedir")
            list(APPEND ENABLED_LIBRARIES UntitledXDGBasedir)
        else()
            find_package(PkgConfig REQUIRED)
            pkg_check_modules(UntitledXDGBasedir REQUIRED UntitledXDGBasedir)

            link_directories(${UntitledXDGBasedir_LIBRARY_DIRS})
            list(APPEND LM_INCLUDE_DIRS ${UntitledXDGBasedir_INCLUDE_DIRS})
            list(APPEND ENABLED_LIBRARIES UntitledXDGBasedir)
            pkg_get_variable(UXDG_COMPILE_DEFS UntitledXDGBasedir compile_defs)
            list(APPEND VENDOR_COMPILE_DEFS ${UXDG_COMPILE_DEFS})
        endif()
    endif()

    option(ENABLE_DBUS_UTILS "Compile in additional utility functions that make using the C DBus API safer" OFF)
    if (ENABLE_DBUS_UTILS)
        find_package(PkgConfig REQUIRED)

        if (BUILD_VARIANT_VENDOR)
            add_subdirectory("${UIMGUI_SRC_PREFIX}/Framework/Modules/OS/ThirdParty/UntitledDBusUtils")
            include_directories(${UntitledDBusUtils_INCLUDE_DIRS})
            list(APPEND ENABLED_LIBRARIES UntitledDBusUtils)
        else()
            pkg_check_modules(UntitledDBusUtils REQUIRED UntitledDBusUtils)

            link_directories(${UntitledDBusUtils_LIBRARY_DIRS})
            string(REPLACE " " ";" DBUS_DIRS "${UntitledDBusUtils_INCLUDE_DIRS}")
            include_directories(${DBUS_DIRS})
            list(APPEND ENABLED_LIBRARIES UntitledDBusUtils)
            pkg_get_variable(UDBUS_COMPILE_DEFS UntitledDBusUtils compile_defs)
            list(APPEND VENDOR_COMPILE_DEFS ${UDBUS_COMPILE_DEFS})
        endif()
    endif()
endmacro()

macro(setup_platform_additional_graphics_backends)
endmacro()

macro(setup_app_sources)
endmacro()

macro(setup_platform_imgui_sources)
endmacro()

macro(setup_opengl_loader_sources)
    setup_opengl_loader_sources_generic(OFF)
endmacro()

macro(setup_platform_target_settings)
    setup_platform_target_settings_generic()
    target_compile_definitions(${APP_LIB_TARGET} PRIVATE "URLL_USE_FUNCTIONAL" "MLS_EXPORT_LIBRARY")

    multicast(target_compile_definitions PRIVATE "UIMGUI_PLATFORM_UNIX")
endmacro()

macro(initialise_platform)
endmacro()

macro(link_to_framework_libraries)
    link_to_framework_libraries_generic_unix()
    if (USE_OS_MODULE)
        if (ENABLE_DBUS_UTILS)
            if (NOT UIMGUI_SKIP_FRAMEWORK)
                target_link_libraries(UntitledImGuiFramework ${DBUS_LIBRARIES})
            endif()
            target_link_libraries(${APP_LIB_TARGET} ${DBUS_LIBRARIES})
        endif()
        if (ENABLE_UFONT_UTILS)
        endif()
    endif()
endmacro()