//
// Created by i-use-gentoo-btw on 4/20/23.
//

#ifndef UNTITLEDLINUXGAMEMANAGER_CTITLEBARCOMPONENT_HPP
#define UNTITLEDLINUXGAMEMANAGER_CTITLEBARCOMPONENT_HPP


class CTitlebarComponent {

};


#endif //UNTITLEDLINUXGAMEMANAGER_CTITLEBARCOMPONENT_HPP
