//
// Created by i-use-gentoo-btw on 4/20/23.
//

#ifndef UNTITLEDLINUXGAMEMANAGER_CWINDOWCOMPONENT_HPP
#define UNTITLEDLINUXGAMEMANAGER_CWINDOWCOMPONENT_HPP


class CWindowComponent {

};


#endif //UNTITLEDLINUXGAMEMANAGER_CWINDOWCOMPONENT_HPP
